CREATE TABLE IF NOT EXISTS public.employee (
  emp_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           varchar(50)  NOT NULL,
  family         varchar(50)  NOT NULL,
  national_id    varchar(20)  NOT NULL,
  birthdate      date         NOT NULL,
  "position"     varchar(50)  NOT NULL,
  username       varchar(50)  NOT NULL,
  password       varchar(255) NOT NULL,
  access_level   integer      NOT NULL,
  CONSTRAINT employee_access_level_check CHECK (access_level >= 1 AND access_level <= 5),
  CONSTRAINT employee_national_id_key UNIQUE (national_id),
  CONSTRAINT employee_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.guest (
  guest_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         varchar(50)  NOT NULL,
  family       varchar(50)  NOT NULL,
  national_id  varchar(20),
  passport     varchar(20),
  birthdate    date         NOT NULL,
  email        varchar(100) NOT NULL,
  CONSTRAINT chk_guest_id CHECK (national_id IS NOT NULL OR passport IS NOT NULL),
  CONSTRAINT guest_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.room (
  room_id    integer PRIMARY KEY,
  type       varchar(30)   NOT NULL,
  capacity   integer       NOT NULL,
  price      numeric(10,2) NOT NULL,
  features   varchar(255),
  floor      integer       NOT NULL,
  bed_type   varchar(30)   NOT NULL,
  smoking    boolean       NOT NULL DEFAULT false,
  status     varchar(20)   NOT NULL,
  CONSTRAINT chk_room_status CHECK (status IN ('available','reserved','occupied','cleaning')),
  CONSTRAINT room_capacity_check CHECK (capacity > 0),
  CONSTRAINT room_price_check CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS public.reservation (
  res_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guest_id      integer NOT NULL,
  emp_id        integer NOT NULL,
  check_in      date    NOT NULL,
  check_out     date    NOT NULL,
  booking_date  timestamp without time zone NOT NULL DEFAULT now(),
  num_people    integer NOT NULL,
  status        varchar(20) NOT NULL,
  total_cost    numeric(10,2) NOT NULL,
  payment       numeric(10,2) NOT NULL DEFAULT 0,
  discount      numeric(5,2)  NOT NULL DEFAULT 0,

  CONSTRAINT chk_res_status CHECK (status IN ('active','canceled','finished')),
  CONSTRAINT chk_reservation_dates CHECK (check_out > check_in),
  CONSTRAINT reservation_num_people_check CHECK (num_people > 0),
  CONSTRAINT reservation_total_cost_check CHECK (total_cost >= 0),
  CONSTRAINT reservation_payment_check CHECK (payment >= 0),
  CONSTRAINT reservation_discount_check CHECK (discount >= 0)
);

CREATE TABLE IF NOT EXISTS public.employee_phone (
  phone_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id    integer NOT NULL,
  phone     varchar(20) NOT NULL,
  CONSTRAINT uq_employee_phone UNIQUE (emp_id, phone)
);

CREATE TABLE IF NOT EXISTS public.guest_phone (
  phone_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guest_id  integer NOT NULL,
  phone     varchar(20) NOT NULL,
  CONSTRAINT uq_guest_phone UNIQUE (guest_id, phone)
);

CREATE TABLE IF NOT EXISTS public.guest_address (
  address_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guest_id   integer NOT NULL,
  province   varchar(50)  NOT NULL,
  city       varchar(50)  NOT NULL,
  street     varchar(100) NOT NULL,
  plaque     varchar(20)  NOT NULL
);

CREATE TABLE IF NOT EXISTS public.employee_guest (
  emp_id   integer NOT NULL,
  guest_id integer NOT NULL,
  CONSTRAINT employee_guest_pkey PRIMARY KEY (emp_id, guest_id)
);

CREATE TABLE IF NOT EXISTS public.reservation_room (
  res_id  integer NOT NULL,
  room_id integer NOT NULL,
  CONSTRAINT reservation_room_pkey PRIMARY KEY (res_id, room_id)
);

ALTER TABLE public.employee_phone
  ADD CONSTRAINT fk_employee_phone
  FOREIGN KEY (emp_id) REFERENCES public.employee(emp_id)
  ON DELETE CASCADE;

ALTER TABLE public.guest_phone
  ADD CONSTRAINT fk_guest_phone
  FOREIGN KEY (guest_id) REFERENCES public.guest(guest_id)
  ON DELETE CASCADE;

ALTER TABLE public.guest_address
  ADD CONSTRAINT fk_guest_address
  FOREIGN KEY (guest_id) REFERENCES public.guest(guest_id)
  ON DELETE CASCADE;

ALTER TABLE public.employee_guest
  ADD CONSTRAINT fk_eg_emp
  FOREIGN KEY (emp_id) REFERENCES public.employee(emp_id)
  ON DELETE CASCADE;

ALTER TABLE public.employee_guest
  ADD CONSTRAINT fk_eg_guest
  FOREIGN KEY (guest_id) REFERENCES public.guest(guest_id)
  ON DELETE CASCADE;

ALTER TABLE public.reservation
  ADD CONSTRAINT fk_res_guest
  FOREIGN KEY (guest_id) REFERENCES public.guest(guest_id);

ALTER TABLE public.reservation
  ADD CONSTRAINT fk_res_emp
  FOREIGN KEY (emp_id) REFERENCES public.employee(emp_id);

ALTER TABLE public.reservation_room
  ADD CONSTRAINT fk_rr_res
  FOREIGN KEY (res_id) REFERENCES public.reservation(res_id)
  ON DELETE CASCADE;

ALTER TABLE public.reservation_room
  ADD CONSTRAINT fk_rr_room
  FOREIGN KEY (room_id) REFERENCES public.room(room_id);